version: '3.3'

services:
  aws:
    image: localstack/localstack
    environment:
      EDGE_PORT: 8080
      SERVICES: lambda, events, iam
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
    ports:
      - "8080:8080"
